print(' Exercício Python 7: Desenvolva um programa que leia as duas notas de um aluno, calcule e mostre a sua média. ')
n1 = float(input(' Qual foi sua 1ª nota?\n R: '))
n2 = float(input(' Qual foi sua 2ª nota?\n R: '))
n3 = float(input(' Qual foi sua 3ª nota?\n R: '))
print(' Sua média foi {:.2f}. '.format((n1 + n2 + n3) / 3))
